# Generated by Django 3.1.5 on 2021-01-07 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('Order_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Order ID')),
                ('Customer_Name', models.CharField(max_length=50)),
                ('Customer_Number', models.CharField(blank=True, max_length=10, null=True)),
                ('item_1', models.CharField(max_length=10)),
                ('item_2', models.CharField(blank=True, max_length=10, null=True)),
                ('item_3', models.CharField(blank=True, max_length=10, null=True)),
                ('item_4', models.CharField(blank=True, max_length=10, null=True)),
                ('item_5', models.CharField(blank=True, max_length=10, null=True)),
                ('Total_Cost', models.CharField(max_length=5)),
                ('Received_By', models.CharField(max_length=10)),
                ('order_date', models.DateField(default=datetime.date(2021, 1, 7))),
                ('order_time', models.TimeField(default=datetime.datetime(2021, 1, 7, 15, 37, 35, 5976))),
                ('Status', models.BooleanField(default=False, verbose_name='Delivered')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50)),
                ('item_name', models.CharField(blank=True, max_length=50)),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('receive_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('received_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issue_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_to', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateField(default=datetime.date(2021, 1, 7))),
            ],
        ),
    ]
