# Generated by Django 3.1.5 on 2021-01-11 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0002_auto_20210109_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='order_date',
            field=models.DateField(default=datetime.date(2021, 1, 11)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 11, 14, 14, 21, 204706)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_added',
            field=models.DateField(default=datetime.date(2021, 1, 11)),
        ),
    ]
