# Generated by Django 3.1.5 on 2021-01-13 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0003_auto_20210111_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='order_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_added',
            field=models.DateField(default=datetime.date(2021, 1, 13)),
        ),
    ]
