# Generated by Django 3.1.5 on 2021-01-13 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0004_auto_20210113_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date_added',
        ),
    ]
